### ISSUE TITLE
re-using words?

### ISSUE THREAD

**Issue by hymie0** [saiftynet/Wordle#2]
I honestly don't know the game, so I don't know if this is a bug or correct behavior.

I play a game and start with a word "REACH" ... I eventually win the game, and answer "Want another game?" with "Yes".

REACH is now an invalid word because I've used it already.

All I have to do is never say "Yes", and always play a fresh new game, and the problem goes away, so I suspect it's a bug.

**Comment by hymie0** [comment]
I guess, at the start of

#main game loop  
while ($firstLoad || prompt("\nWant another game Y/N?")=~/^y/i){

you probably need to reset all of the validWords entries to be 1.

**Comment by saiftynet** [comment]
Agreed, need to reset the words hash back to 1.

**Comment by saiftynet** [comment]
Thank you for your bug checking; issues addressed
