### ISSUE TITLE
perl errors Use of uninitialized value

### ISSUE THREAD

**Issue by hymie0** [saiftynet/Wordle#3]
Getting lots of errors that look like this:

Use of uninitialized value $keyboard[3] in substitution (s///) at wordle.pl line 113, <STDIN> line 1.
Use of uninitialized value $keyboard[3] in substitution (s///) at wordle.pl line 113, <STDIN> line 1.
Use of uninitialized value $keyboard[4] in substitution (s///) at wordle.pl line 113, <STDIN> line 1.

Need this patch around line 110-ish

        foreach my $gc(split (//,$guess)){
            my $c=($answer=~/$gc/)?color("cyan"):color("red");
            my $r=color("reset");
-               foreach my $kbRow (0..@keyboard){
+               foreach my $kbRow (0..$#keyboard){
                        $keyboard[$kbRow]=~s/ $gc / $c$gc$r /;
                }
        }

**Comment by saiftynet** [comment]
Hopefully fixed, thanks

**Comment by saiftynet** [comment]
Committed and credited
