### ISSUE TITLE
add failure to statistics screen

### ISSUE THREAD

**Issue by hymie0** [saiftynet/Wordle#4]
I like the new statistics screen.  Request that you add a count of games lost.  It should line up with the single-digits that you already have.  Perhaps L ?   F ?   X ?

**Comment by saiftynet** [comment]
Is this what you mean?
![image](https://user-images.githubusercontent.com/34284663/152874045-267456b4-15fa-42ce-aeb8-28c86b76009f.png)

**Comment by saiftynet** [comment]
committed
